services:
  db:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - "97576e2b42f4b9a1b78761b067a6e7008151316b11a02be51a3362408d8def68:/var/lib/mysql"
      - "./migrations/migration.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
  http:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

volumes:
  97576e2b42f4b9a1b78761b067a6e7008151316b11a02be51a3362408d8def68:
    external: true
